/* src/types/actions.ts */
export const ACTION_TYPES = {
  // Document Actions
  LOAD_DOCUMENT: 'LOAD_DOCUMENT',
  LOAD_SOUNDS: 'LOAD_SOUNDS',
  CLEAR_PROJECT: 'CLEAR_PROJECT',
  UPDATE_LINE: 'UPDATE_LINE', // Added UPDATE_LINE

  // Navigation Actions
  SELECT_LINE: 'SELECT_LINE',
  NAVIGATE_UP: 'NAVIGATE_UP',
  NAVIGATE_DOWN: 'NAVIGATE_DOWN',
  NAVIGATE_NEXT_LINE: 'NAVIGATE_NEXT_LINE',
  NAVIGATE_PREVIOUS_LINE: 'NAVIGATE_PREVIOUS_LINE',

  // Sound Cue Actions
  PLAY_SOUND_CUE: 'PLAY_SOUND_CUE',
  STOP_SOUND_CUE: 'STOP_SOUND_CUE',
  TOGGLE_PLAY_SOUND_CUE: 'TOGGLE_PLAY_SOUND_CUE',

  // Search Actions
  SEARCH_QUERY_CHANGED: 'SEARCH_QUERY_CHANGED',
  NAVIGATE_NEXT_MATCH: 'NAVIGATE_NEXT_MATCH',
  NAVIGATE_PREVIOUS_MATCH: 'NAVIGATE_PREVIOUS_MATCH',
} as const;

export interface Action {
  type: keyof typeof ACTION_TYPES;
  payload?: any;
}
